services:
  - type: web
    name: modelflow-mlops-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    region: oregon
    plan: free
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
      - key: MODEL_PATH
        value: artifacts/models/champion_model.joblib
      - key: METADATA_PATH
        value: artifacts/models/model_metadata.json
      - key: REFERENCE_DATA_PATH
        value: data/processed/train.csv
      - key: MLFLOW_TRACKING_URI
        value: sqlite:///mlflow.db
      - key: CORS_ORIGINS
        value: '["https://model-flow-mlops.vercel.app","http://localhost:3000"]'
